name: Feature Request
description: Request a new feature or an enhancement to an existing feature.
title: '[feat]: '
labels: ['feature', 'triage']
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to see changed or added?
      placeholder: Description
  - type: textarea
    id: audience
    attributes:
      label: Audience
      description: Who would benefit from this feature (e.g. users, administrators)?
      placeholder: Audience
  - type: textarea
    id: benefit
    attributes:
      label: Benefits
      description: How would this feature help the audience?
      placeholder: Benefits
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Are there alternative features that might work?
      placeholder: Alternatives
